name: Run Hardhat Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    name: Run hardhat tests on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    env:
      ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
      ANKR_API_KEY: ${{ secrets.ANKR_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm install
      - name: Run tests
        run: npx hardhat test
